// <auto-generated />
namespace LocationMotos_ASP.Net_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creationBdMotoAuth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creationBdMotoAuth));
        
        string IMigrationMetadata.Id
        {
            get { return "202201080345144_creationBdMotoAuth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
